### ISSUE TITLE
svn directory error

### ISSUE THREAD

**Issue by DenisVS** [b-ryan/powerline-shell#344]
`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/segments/svn.py", line 38, in run
    self.revision = line.split(" ", maxsplit=1)[1]
TypeError: split() takes no keyword arguments
`
![1](https://user-images.githubusercontent.com/12385211/34555593-00286c1c-f14c-11e7-9e93-68cc19595e05.png)
` uname -a
FreeBSD local 10.2-STABLE FreeBSD 10.2-STABLE #0 r289019: Thu Oct  8 15:00:20 MSK 2015   local:/usr/obj/usr/src/sys/GENERIC  amd64`

**Comment by kc9jud** [comment]
Oops, I introduced this in 7679889... this seems to be a Python 3-ism...
