### ISSUE TITLE
segement configuration - hostname colorize

### ISSUE THREAD

**Issue by comagnaw** [b-ryan/powerline-shell#353]
Got following stacktrace on an alternative workstation when I enabled hostname colorize:

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 205, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/segments/hostname.py", line 13, in add_to_powerline
    FG, BG = (rgb2short(*color) for color in [FG, BG])
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/segments/hostname.py", line 13, in <genexpr>
    FG, BG = (rgb2short(*color) for color in [FG, BG])
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/colortrans.py", line 312, in rgb2short
    return RGB2SHORT_DICT[tuple(res)]
KeyError: (95, 255)
```

Did some debugging and narrowed it down to `color_complement.getOppositeColor()`.  I see there are checks for max numbers but nothing for minimum numbers.   It is the negative number that is causing the stacktrace when [hostname.add_to_powerline, line 13](https://github.com/b-ryan/powerline-shell/blob/master/powerline_shell/segments/hostname.py#L13) tries to process the first set of FG/BG that the stacktrace occurs.  Below is ptpython output of my debug of `getOppositeColor`.  You can see the return is **(49, -1, 254)**.

```
>>> def getOppositeColor(r,g,b):
...     print "r:", r, "g:", g, "b:", b
...     hls = rgb_to_hls(r,g,b)
...     print "hls:", hls
...     opp = list(hls[:])
...     opp[0] = (opp[0]+0.2)%1 # shift hue (a.k.a. color)
...     print "r:", r, "opp of r:", opp[0]
...     if opp[1] > 255/2:   # for level you want to make sure they
...         opp[1] -= 255/2  # are quite different so easily readable
...     else:
...         opp[1] += 255/2
...     print "g:", g, "opp of g:", opp[1]
...     if opp[2] > -0.5: # if saturation is low on first color increase second's
...         opp[2] -= 0.5
...     print "b:", b, "opp of b:", opp[2]
...     print "opp:", opp
...     opp = hls_to_rgb(*opp)
...     print "hls_to_rgb:", opp
...     mx = max(opp)
...     mn = min(opp)
...     print "max:", mx, "min:", mn
...     if mx > 255: #colorsys module doesn't give caps to their conversions
...         opp = [ x*254/mx for x in opp]
...     return tuple([ int(x) for x in opp])

>>> getOppositeColor(*color1)
r: 0 g: 10 b: 131
hls: (0.5, 65.5, -1.0155038759689923)
r: 0 opp of r: 0.7
g: 10 opp of g: 192.5
b: 131 opp of b: -1.01550387597
opp: [0.7, 192.5, -1.0155038759689923]
hls_to_rgb: (75.8186046511625, -1.9689922480620226, 386.968992248062)
max: 386.968992248 min: -1.96899224806
(49, -1, 254)
```

I am not a rgb/hls expert and not certain of what the proper range of returns when going between rgb and hls.  However, in this case the b value of 131 appears to not return a value outside scope of formatting rules on `opp[2]`.

Just my $.02.... 
Not sure if colorize could be improved by allowing user to provides rgb value for colorize of hostname, or hard code it into themes.  This could simplify the handling of colorize and make customization obtainable by the user.  Added bonus, the hostname color is predictable and not random....I really like the colorize feature but don't want to see this for a hostname color:

![screen shot 2018-02-01 at 10 01 23 am](https://user-images.githubusercontent.com/11246499/35685209-0a22ed9a-0737-11e8-8eb7-5b85510a2fea.png)

**Comment by comagnaw** [comment]
More investigation into this problem and it appears fix is to convert the rgb values to float before passing to `rgb_to_hls`.  See stackoverflow answer here:

https://stackoverflow.com/questions/15442285/converting-rgb-to-hls-and-back

Below is a getOppositeColor without and with conversion to float.  The results look good.  
```
#
# Without conversion to float
#
>>> def getOppositeColor(r,g,b):
...         print "original - r:", r, "g:", g, "b:", b
...         #r, g, b = [x/255.0 for x in r, g, b]
...         #print "rgb into float - r:", r, "g:", g, "b:", b
...
...         hls = rgb_to_hls(r,g,b)
...         print "rgb_to_hls:", hls
...         opp = list(hls[:])
...         opp[0] = (opp[0]+0.2)%1 # shift hue (a.k.a. color)
...         if opp[1] > 255/2:   # for level you want to make sure they
...             opp[1] -= 255/2  # are quite different so easily readable
...         else:
...             opp[1] += 255/2
...         if opp[2] > -0.5: # if saturation is low on first color increase second's
...             opp[2] -= 0.5
...         opp = hls_to_rgb(*opp)
...         print "opp:", opp
...         mx = max(opp)
...         if mx > 255: #colorsys module doesn't give caps to their conversions
...             opp = [ x*255/mx for x in opp]
...         return tuple([ int(x) for x in opp])

# Out of bounds RGB values....who knew?
>>> color1 = (0, 10, 131)

# Negative value returned
>>> getOppositeColor(*color1)
original - r: 0 g: 10 b: 131
rgb_to_hls: (0.5, 65.5, -1.0155038759689923)
opp: (75.8186046511625, -1.9689922480620226, 386.968992248062)
(49, -1, 255)

#
# With conversion to float
#
>>> def getOppositeColor(r,g,b):
...         print "original - r:", r, "g:", g, "b:", b
...         r, g, b = [x/255.0 for x in r, g, b]
...         print "rgb into float - r:", r, "g:", g, "b:", b
...
...         hls = rgb_to_hls(r,g,b)
...         print "rgb_to_hls:", hls
...         opp = list(hls[:])
...         opp[0] = (opp[0]+0.2)%1 # shift hue (a.k.a. color)
...         if opp[1] > 255/2:   # for level you want to make sure they
...             opp[1] -= 255/2  # are quite different so easily readable
...         else:
...             opp[1] += 255/2
...         if opp[2] > -0.5: # if saturation is low on first color increase second's
...             opp[2] -= 0.5
...         opp = hls_to_rgb(*opp)
...         print "opp:", opp
...         mx = max(opp)
...         if mx > 255: #colorsys module doesn't give caps to their conversions
...             opp = [ x*255/mx for x in opp]
...         return tuple([ int(x) for x in opp])

# Happy results without negative numbers.
>>> getOppositeColor(*color1)
original - r: 0 g: 10 b: 131
rgb into float - r: 0.0 g: 0.0392156862745 b: 0.513725490196
rgb_to_hls: (0.6539440203562341, 0.2568627450980392, 1.0)
opp: (64.12843137254902, 190.38529411764705, 79.74187546774439)
(64, 190, 79)
```

Probably would be good to have unittest which iterates through six digit hex string range 0x000000 through 0xffffff and asserting error if negative number is found in the tuple.
