### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by znack2** [b-ryan/powerline-shell#371]
`Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/powerline_shell/__init__.py", line 204, in main
    config = json.loads(f.read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

install by sudo pip install powerline-shell
use new version python 

what should i do to fix it?

**Comment by b-ryan** [comment]
At first glance it looks like you have a configuration file, but the file does not contain json. Do you have a file at `~/.powerline-shell.json`?
