### ISSUE TITLE
Python3 Compatibility Issue 

### ISSUE THREAD

**Issue by stalinkay** [b-ryan/powerline-shell#378]
I'm getting the following stack trace on macOS High Sierra. [See this question for a possible solution](https://stackoverflow.com/questions/8427352/how-to-solve-attributeerror-environ-object-has-no-attribute-has-key)

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/powerline_shell/__init__.py", line 218, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python3.6/site-packages/powerline_shell/segments/ruby_version.py", line 13, in add_to_powerline
    if os.environ.has_key("GEM_HOME"):
AttributeError: '_Environ' object has no attribute 'has_key'
```

**Comment by b-ryan** [comment]
Was fixed in https://github.com/b-ryan/powerline-shell/pull/366

**Comment by stalinkay** [comment]
@b-ryan Thanks.
