### ISSUE TITLE
SIGINT prints Python stack trace

### ISSUE THREAD

**Issue by timhwang21** [b-ryan/powerline-shell#393]
Hi, thanks for all your hard work on this package!

I'm wondering if you think this issue is worth fixing. I've found that SIGINTs cause the following stack trace to be printed:

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 224, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/segments/git_stash.py", line 25, in add_to_powerline
    self.join()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

^CTraceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 224, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/segments/git.py", line 71, in add_to_powerline
    self.join()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

Is it currently possible to suppress this output, and if not, is it worth fixing? Thanks!

**Comment by timhwang21** [comment]
Additionally, hitting ctrl-c twice in quick succession triggers this for me:

```
^CTraceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 7, in <module>
    from powerline_shell import main
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/__init__.py", line 9, in <module>
    from .utils import warn, py3, import_file
  File "/usr/local/lib/python2.7/site-packages/powerline_shell/utils.py", line 3, in <module>
    import threading
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 15, in <module>
    from time import time as _time, sleep as _sleep
KeyboardInterrupt
```

**Comment by lehaininh** [comment]
I'm having this same problem with Ctrl-C. Any solution?
