### ISSUE TITLE
BUG in SVN segment when there's a SVN changelist

### ISSUE THREAD

**Issue by tberne** [b-ryan/powerline-shell#403]
I suppose its a matter of ignoring blank lines. Error below:

![bug-svn_withchangelist](https://user-images.githubusercontent.com/10933706/40023524-bbca78a0-57a1-11e8-8952-d007dd5254b7.png)

**Comment by tberne** [comment]
Error as txt:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/powerline_shell/segments/svn.py", line 59, in run
    self.stats, self.revision = build_stats()
  File "build/bdist.linux-x86_64/egg/powerline_shell/segments/svn.py", line 47, in build_stats
    stats = parse_svn_stats(status)
  File "build/bdist.linux-x86_64/egg/powerline_shell/segments/svn.py", line 20, in parse_svn_stats
    if line[0] == "?":
IndexError: string index out of range
```
