### ISSUE TITLE
Twice CTRL + C or more causes error

### ISSUE THREAD

**Issue by onhernandes** [b-ryan/powerline-shell#445]
Sometimes I need to stop/kill some current command with `CTRL + C`. When I press the keys twice, I got an error and then powerline shows up again. Is this normal? (because I'm pressing `CTRL + C` multiple times)

```shell
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.7/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.7/site.py", line 557, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib/python3.7/site.py", line 349, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 835, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
KeyboardInterrupt

```

**Comment by rkraneis** [comment]
Same here. Just keeping CTRL+C pressed until auto repeat kicks leads (of course) to the same problem (but more stack traces, as powerline gets killed repeatedly). Not sure if anything can be done about this.

**Comment by b4dpxl** [comment]
Changing the `powerline-shell` file to add a `try|except` like this worked for me:
```python
if __name__ == '__main__':
    try:
        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(main())
    except KeyboardInterrupt:
        pass
```
