### ISSUE TITLE
User segment failing on windows with UnicodeEncodeError

### ISSUE THREAD

**Issue by stuaxo** [b-ryan/powerline-shell#452]
On git-bash on Windows, the User segment is giving me a unicode error.

Python is 3.7, running with bash from git.

```
Traceback (most recent call last):
  File "C:\Users\A642177\AppData\Local\Programs\Python\Python37\Scripts\powerline-shell-script.py", line 11, in <module>
    load_entry_point('powerline-shell', 'console_scripts', 'powerline-shell')()
  File "j:\powerline-shell\powerline_shell\__init__.py", line 243, in main
    sys.stdout.write(powerline.draw())
  File "C:\Users\A642177\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ue0b0' in position 61: character maps to <undefined>
```

**Comment by danielschenk** [comment]
I managed to work around this by:

1. Configuring git-bash for UTF-8:
   ![image](https://user-images.githubusercontent.com/9695838/63590449-222e0980-c5ac-11e9-8f4b-ed6d416881d0.png)
2. Adding this to my `.bashrc`:
   ```sh
   export PYTHONIOENCODING="utf-8"
   ```

However, if powerline-shell could handle this somehow that would be nice. Not sure if it should though, it appears to be an issue between Python and MSYS.

**Comment by stuaxo** [comment]
Ah, this makes sense !

It looks like it might be possible to run the ordinary windows console with UTF-8 too, as well as setting the font you need to set the codepage `chcp 65001`.

Can you test that as well ?

https://stackoverflow.com/questions/19955385/utf-8-in-windows-7-cmd

**Comment by stuaxo** [comment]
Looks like my issue is running windows python from Mintty, I haven't worked out a reliable way getting powershell to work that way.

@b-ryan is it possible to merge the fix for PS under windows now there is confirmation it works ?

**Comment by stuaxo** [comment]
Confirming this fix gets things working for non-windows python inside mintty (linux python in docker).

**Comment by pjirsa** [comment]
This workaround worked for me. However, i'm not seeing any colors. It's all grayscale with bit bash for windows. 
I installed for WSL and everything looks good. Does anyone have an idea why there are no colors when using git bash?
