### ISSUE TITLE
Missing libffi6 when installing on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by IamGianluca** [b-ryan/powerline-shell#494]
Hi, 

Thank you for the wonderful tool! 

I've recently upgraded to Ubuntu 20.04 LTS and tried to install powerline-shell from the Git repository. This is the error message I see:

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
  File "/home/gianluca/.pyenv/versions/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/home/gianluca/.pyenv/versions/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/home/gianluca/.pyenv/versions/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/gianluca/.pyenv/versions/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

Ubuntu 20.04 LTS doesn't have `libffi6`, instead, it comes with `libffi7` already installed. I've tried to install `libffi6` but it doesn't ship with this new version of Ubuntu.

```
$ sudo apt-get install libffi6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libffi6
$ sudo apt-get install libffi7
[sudo] password for gianluca: 
Sorry, try again.
[sudo] password for gianluca: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi7 is already the newest version (3.3-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by IamGianluca** [comment]
FYI, installing via `pip install powerline-shell` on the same OS works.
