### ISSUE TITLE
Exception navigating into subversion folder

### ISSUE THREAD

**Issue by bwm-projects** [b-ryan/powerline-shell#554]
Getting exception when I navigate into my SVN folder: AttributeError: 'Segment' object has no attribute 'stats'.   Is there a fix for this?  

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/bmaynard/.local/lib/python3.8/site-packages/powerline_shell/segments/svn.py", line 54, in run
    self.stats, self.revision = build_stats()
  File "/home/bmaynard/.local/lib/python3.8/site-packages/powerline_shell/segments/svn.py", line 47, in build_stats
    stats = parse_svn_stats(status)
  File "/home/bmaynard/.local/lib/python3.8/site-packages/powerline_shell/segments/svn.py", line 20, in parse_svn_stats
    if line[0] == "?":
IndexError: string index out of range
Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/home/bmaynard/.local/lib/python3.8/site-packages/powerline_shell/__init__.py", line 240, in main
    segment.add_to_powerline()
  File "/home/bmaynard/.local/lib/python3.8/site-packages/powerline_shell/segments/svn.py", line 58, in add_to_powerline
    if not self.stats:
AttributeError: 'Segment' object has no attribute 'stats'

**Comment by bwm-projects** [comment]
Fixed it myself.

In /powerline_shell/segments/svn.py:

def parse_svn_stats(status):
    stats = RepoStats()

    for line in status:
        if len(line) > 0:  # added this line to fix exception
            if line[0] == "?":
                stats.new += 1
            elif line[0] == "C":
                stats.conflicted += 1
            elif line[0] in ["A", "D", "I", "M", "R", "!", "~"]:
                stats.changed += 1
    return stats
